name: Continuous Integration

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build and test backend
        run: |
          chmod +x ./gradlew  
          ./gradlew clean build  
          ./gradlew test  
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin  
                  docker build --no-cache -t prince1337/webapp-server:1.0 .  
                  docker push prince1337/webapp-server:1.0
        working-directory: ./web-app

